/**
 * Transaction Knowledge Base & Intelligence Directory
 * Comprehensive vocabulary, patterns, merchants, payment methods, bank nicknames,
 * intent verbs, and Hinglish phrase mappings for accurate financial entry understanding.
 */

export interface MerchantInfo {
  category: string;
  tag: string;
  defaultNote?: string;
}

// ─── 1. Merchant Knowledge Base (1,000+ Merchants mapped to Categories & Tags) ────
export const MERCHANT_KNOWLEDGE: Record<string, MerchantInfo> = {
  // ── Food & Dining ────────────────────────────────────────────────────────
  zomato: { category: 'Food', tag: 'Personal', defaultNote: 'Food Order' },
  swiggy: { category: 'Food', tag: 'Personal', defaultNote: 'Food Delivery' },
  starbucks: { category: 'Food', tag: 'Personal', defaultNote: 'Coffee' },
  mcdonalds: { category: 'Food', tag: 'Personal', defaultNote: 'Fast Food' },
  "mcdonald's": { category: 'Food', tag: 'Personal', defaultNote: 'Fast Food' },
  mcd: { category: 'Food', tag: 'Personal', defaultNote: 'Fast Food' },
  dominos: { category: 'Food', tag: 'Personal', defaultNote: 'Pizza' },
  domino: { category: 'Food', tag: 'Personal', defaultNote: 'Pizza' },
  kfc: { category: 'Food', tag: 'Personal' },
  subway: { category: 'Food', tag: 'Personal' },
  'pizza hut': { category: 'Food', tag: 'Personal' },
  pizzahut: { category: 'Food', tag: 'Personal' },
  'burger king': { category: 'Food', tag: 'Personal' },
  burgerking: { category: 'Food', tag: 'Personal' },
  chai: { category: 'Food', tag: 'Personal' },
  'chai point': { category: 'Food', tag: 'Personal' },
  chaayos: { category: 'Food', tag: 'Personal' },
  coffee: { category: 'Food', tag: 'Personal' },
  cafe: { category: 'Food', tag: 'Personal' },
  haldirams: { category: 'Food', tag: 'Personal' },
  "haldiram's": { category: 'Food', tag: 'Personal' },
  'barbeque nation': { category: 'Food', tag: 'Personal' },
  bbq: { category: 'Food', tag: 'Personal' },
  saravana: { category: 'Food', tag: 'Personal' },
  'biryani by kilo': { category: 'Food', tag: 'Personal' },
  eatfit: { category: 'Food', tag: 'Personal' },
  faasos: { category: 'Food', tag: 'Personal' },
  box8: { category: 'Food', tag: 'Personal' },
  behrouz: { category: 'Food', tag: 'Personal' },
  magicpin: { category: 'Food', tag: 'Personal' },
  dineout: { category: 'Food', tag: 'Personal' },
  eatsure: { category: 'Food', tag: 'Personal' },
  'wow momo': { category: 'Food', tag: 'Personal' },
  wowmomo: { category: 'Food', tag: 'Personal' },
  'baskin robbins': { category: 'Food', tag: 'Personal' },
  naturals: { category: 'Food', tag: 'Personal' },
  dunkin: { category: 'Food', tag: 'Personal' },
  social: { category: 'Food', tag: 'Personal' },
  'third wave coffee': { category: 'Food', tag: 'Personal' },
  'blue tokai': { category: 'Food', tag: 'Personal' },
  'costa coffee': { category: 'Food', tag: 'Personal' },
  restaurant: { category: 'Food', tag: 'Personal' },
  lunch: { category: 'Food', tag: 'Personal' },
  dinner: { category: 'Food', tag: 'Personal' },
  breakfast: { category: 'Food', tag: 'Personal' },
  snacks: { category: 'Food', tag: 'Personal' },
  bakery: { category: 'Food', tag: 'Personal' },
  sweets: { category: 'Food', tag: 'Personal' },
  canteen: { category: 'Food', tag: 'Personal' },
  dhaba: { category: 'Food', tag: 'Personal' },

  // ── Groceries & Daily Essentials ─────────────────────────────────────────
  blinkit: { category: 'Groceries', tag: 'Household', defaultNote: 'Quick Grocery' },
  zepto: { category: 'Groceries', tag: 'Household', defaultNote: 'Quick Grocery' },
  dunzo: { category: 'Groceries', tag: 'Household' },
  bigbasket: { category: 'Groceries', tag: 'Household' },
  grofers: { category: 'Groceries', tag: 'Household' },
  jiomart: { category: 'Groceries', tag: 'Household' },
  instamart: { category: 'Groceries', tag: 'Household' },
  dmart: { category: 'Groceries', tag: 'Household' },
  'd-mart': { category: 'Groceries', tag: 'Household' },
  reliance: { category: 'Groceries', tag: 'Household' },
  'reliance smart': { category: 'Groceries', tag: 'Household' },
  'reliance fresh': { category: 'Groceries', tag: 'Household' },
  more: { category: 'Groceries', tag: 'Household' },
  spencers: { category: 'Groceries', tag: 'Household' },
  'natures basket': { category: 'Groceries', tag: 'Household' },
  'country delight': { category: 'Groceries', tag: 'Household' },
  licious: { category: 'Groceries', tag: 'Household' },
  freshtohome: { category: 'Groceries', tag: 'Household' },
  milkbasket: { category: 'Groceries', tag: 'Household' },
  otipy: { category: 'Groceries', tag: 'Household' },
  bbdaily: { category: 'Groceries', tag: 'Household' },
  'flipkart minutes': { category: 'Groceries', tag: 'Household' },
  vegetables: { category: 'Groceries', tag: 'Household' },
  grocery: { category: 'Groceries', tag: 'Household' },
  supermarket: { category: 'Groceries', tag: 'Household' },
  kirana: { category: 'Groceries', tag: 'Household' },
  ration: { category: 'Groceries', tag: 'Household' },
  dairy: { category: 'Groceries', tag: 'Household' },
  milk: { category: 'Groceries', tag: 'Household' },

  // ── Transport & Mobility ──────────────────────────────────────────────────
  uber: { category: 'Transport', tag: 'Personal', defaultNote: 'Cab Ride' },
  ola: { category: 'Transport', tag: 'Personal', defaultNote: 'Cab Ride' },
  rapido: { category: 'Transport', tag: 'Personal', defaultNote: 'Bike/Auto Ride' },
  irctc: { category: 'Transport', tag: 'Personal', defaultNote: 'Train Ticket' },
  blusmart: { category: 'Transport', tag: 'Personal' },
  meru: { category: 'Transport', tag: 'Personal' },
  nammayatri: { category: 'Transport', tag: 'Personal' },
  'namma yatri': { category: 'Transport', tag: 'Personal' },
  shuttl: { category: 'Transport', tag: 'Personal' },
  chalo: { category: 'Transport', tag: 'Personal' },
  petrol: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  fuel: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  diesel: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  indianoil: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  hpcl: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  bpcl: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  shell: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  nayara: { category: 'Transport', tag: 'Personal', defaultNote: 'Fuel' },
  metro: { category: 'Transport', tag: 'Personal', defaultNote: 'Metro Recharge' },
  auto: { category: 'Transport', tag: 'Personal' },
  taxi: { category: 'Transport', tag: 'Personal' },
  cab: { category: 'Transport', tag: 'Personal' },
  parking: { category: 'Transport', tag: 'Personal' },
  toll: { category: 'Transport', tag: 'Personal' },
  fastag: { category: 'Transport', tag: 'Personal', defaultNote: 'FASTag Recharge' },
  rickshaw: { category: 'Transport', tag: 'Personal' },
  ather: { category: 'Transport', tag: 'Personal', defaultNote: 'EV Charging' },
  'tata power ez': { category: 'Transport', tag: 'Personal' },

  // ── Travel & Accommodations ───────────────────────────────────────────────
  makemytrip: { category: 'Travel', tag: 'Personal' },
  goibibo: { category: 'Travel', tag: 'Personal' },
  redbus: { category: 'Travel', tag: 'Personal' },
  cleartrip: { category: 'Travel', tag: 'Personal' },
  ixigo: { category: 'Travel', tag: 'Personal' },
  airbnb: { category: 'Travel', tag: 'Personal' },
  oyo: { category: 'Travel', tag: 'Personal' },
  yatra: { category: 'Travel', tag: 'Personal' },
  easemytrip: { category: 'Travel', tag: 'Personal' },
  'booking.com': { category: 'Travel', tag: 'Personal' },
  treebo: { category: 'Travel', tag: 'Personal' },
  fabhotels: { category: 'Travel', tag: 'Personal' },
  agoda: { category: 'Travel', tag: 'Personal' },
  indigo: { category: 'Travel', tag: 'Personal', defaultNote: 'Flight Ticket' },
  'air india': { category: 'Travel', tag: 'Personal' },
  akasa: { category: 'Travel', tag: 'Personal' },
  spicejet: { category: 'Travel', tag: 'Personal' },
  vistara: { category: 'Travel', tag: 'Personal' },
  flight: { category: 'Travel', tag: 'Personal' },
  hotel: { category: 'Travel', tag: 'Personal' },
  train: { category: 'Travel', tag: 'Personal' },
  resort: { category: 'Travel', tag: 'Personal' },

  // ── Shopping & Electronics ────────────────────────────────────────────────
  amazon: { category: 'Shopping', tag: 'Personal' },
  flipkart: { category: 'Shopping', tag: 'Personal' },
  myntra: { category: 'Shopping', tag: 'Personal' },
  meesho: { category: 'Shopping', tag: 'Personal' },
  ajio: { category: 'Shopping', tag: 'Personal' },
  nykaa: { category: 'Shopping', tag: 'Personal' },
  snapdeal: { category: 'Shopping', tag: 'Personal' },
  lenskart: { category: 'Shopping', tag: 'Personal' },
  croma: { category: 'Shopping', tag: 'Personal' },
  'reliance digital': { category: 'Shopping', tag: 'Personal' },
  decathlon: { category: 'Shopping', tag: 'Personal' },
  ikea: { category: 'Shopping', tag: 'Personal' },
  'h&m': { category: 'Shopping', tag: 'Personal' },
  zara: { category: 'Shopping', tag: 'Personal' },
  'tata cliq': { category: 'Shopping', tag: 'Personal' },
  firstcry: { category: 'Shopping', tag: 'Personal' },
  'shoppers stop': { category: 'Shopping', tag: 'Personal' },
  westside: { category: 'Shopping', tag: 'Personal' },
  pantaloons: { category: 'Shopping', tag: 'Personal' },
  lifestyle: { category: 'Shopping', tag: 'Personal' },
  uniqlo: { category: 'Shopping', tag: 'Personal' },
  pepperfry: { category: 'Shopping', tag: 'Household' },
  'urban ladder': { category: 'Shopping', tag: 'Household' },
  'vijay sales': { category: 'Shopping', tag: 'Personal' },
  apple: { category: 'Shopping', tag: 'Personal' },
  oneplus: { category: 'Shopping', tag: 'Personal' },
  samsung: { category: 'Shopping', tag: 'Personal' },

  // ── Bills, Subscriptions & Utilities ──────────────────────────────────────
  netflix: { category: 'Bills', tag: 'Personal', defaultNote: 'Subscription' },
  hotstar: { category: 'Bills', tag: 'Personal', defaultNote: 'Subscription' },
  disney: { category: 'Bills', tag: 'Personal', defaultNote: 'Subscription' },
  primevideo: { category: 'Bills', tag: 'Personal', defaultNote: 'Subscription' },
  'amazon prime': { category: 'Bills', tag: 'Personal', defaultNote: 'Subscription' },
  jio: { category: 'Bills', tag: 'Personal', defaultNote: 'Mobile Recharge' },
  airtel: { category: 'Bills', tag: 'Personal', defaultNote: 'Mobile Bill/Recharge' },
  vi: { category: 'Bills', tag: 'Personal', defaultNote: 'Mobile Bill' },
  bsnl: { category: 'Bills', tag: 'Personal', defaultNote: 'Mobile Bill' },
  electricity: { category: 'Bills', tag: 'Household', defaultNote: 'Electricity Bill' },
  bescom: { category: 'Bills', tag: 'Household', defaultNote: 'Electricity Bill' },
  msedcl: { category: 'Bills', tag: 'Household', defaultNote: 'Electricity Bill' },
  tneb: { category: 'Bills', tag: 'Household', defaultNote: 'Electricity Bill' },
  bses: { category: 'Bills', tag: 'Household', defaultNote: 'Electricity Bill' },
  water: { category: 'Bills', tag: 'Household', defaultNote: 'Water Bill' },
  gas: { category: 'Bills', tag: 'Household', defaultNote: 'Gas Cylinder/Bill' },
  indane: { category: 'Bills', tag: 'Household', defaultNote: 'Gas Cylinder' },
  bharatgas: { category: 'Bills', tag: 'Household', defaultNote: 'Gas Cylinder' },
  hpgas: { category: 'Bills', tag: 'Household', defaultNote: 'Gas Cylinder' },
  igl: { category: 'Bills', tag: 'Household', defaultNote: 'Piped Gas' },
  mgl: { category: 'Bills', tag: 'Household', defaultNote: 'Piped Gas' },
  insurance: { category: 'Bills', tag: 'Personal', defaultNote: 'Insurance Premium' },
  lic: { category: 'Bills', tag: 'Personal', defaultNote: 'LIC Premium' },
  'tata play': { category: 'Bills', tag: 'Household', defaultNote: 'DTH Recharge' },
  dishtv: { category: 'Bills', tag: 'Household', defaultNote: 'DTH Recharge' },
  hathway: { category: 'Bills', tag: 'Household', defaultNote: 'Broadband Bill' },
  'act fibernet': { category: 'Bills', tag: 'Household', defaultNote: 'Broadband Bill' },
  broadband: { category: 'Bills', tag: 'Household', defaultNote: 'Broadband Bill' },
  wifi: { category: 'Bills', tag: 'Household', defaultNote: 'WiFi Bill' },
  dth: { category: 'Bills', tag: 'Household', defaultNote: 'DTH Bill' },
  recharge: { category: 'Bills', tag: 'Personal', defaultNote: 'Recharge' },
  postpaid: { category: 'Bills', tag: 'Personal', defaultNote: 'Postpaid Bill' },
  prepaid: { category: 'Bills', tag: 'Personal', defaultNote: 'Prepaid Recharge' },
  chatgpt: { category: 'Bills', tag: 'Work', defaultNote: 'AI Subscription' },
  openai: { category: 'Bills', tag: 'Work', defaultNote: 'AI API Subscription' },
  github: { category: 'Bills', tag: 'Work', defaultNote: 'GitHub Subscription' },
  hostinger: { category: 'Bills', tag: 'Work', defaultNote: 'Hosting Bill' },
  vercel: { category: 'Bills', tag: 'Work', defaultNote: 'Cloud Hosting' },
  aws: { category: 'Bills', tag: 'Work', defaultNote: 'AWS Cloud Services' },
  'google cloud': { category: 'Bills', tag: 'Work' },
  canva: { category: 'Bills', tag: 'Work' },
  adobe: { category: 'Bills', tag: 'Work' },
  icloud: { category: 'Bills', tag: 'Personal', defaultNote: 'Apple iCloud' },
  'youtube premium': { category: 'Bills', tag: 'Personal' },

  // ── Entertainment & Leisure ───────────────────────────────────────────────
  spotify: { category: 'Entertainment', tag: 'Personal', defaultNote: 'Music Subscription' },
  bookmyshow: { category: 'Entertainment', tag: 'Personal', defaultNote: 'Movie Tickets' },
  'book my show': { category: 'Entertainment', tag: 'Personal' },
  pvr: { category: 'Entertainment', tag: 'Personal', defaultNote: 'Movie' },
  inox: { category: 'Entertainment', tag: 'Personal', defaultNote: 'Movie' },
  cinepolis: { category: 'Entertainment', tag: 'Personal' },
  movie: { category: 'Entertainment', tag: 'Personal' },
  cinema: { category: 'Entertainment', tag: 'Personal' },
  concert: { category: 'Entertainment', tag: 'Personal' },
  gaming: { category: 'Entertainment', tag: 'Personal' },
  steam: { category: 'Entertainment', tag: 'Personal' },
  playstation: { category: 'Entertainment', tag: 'Personal' },
  xbox: { category: 'Entertainment', tag: 'Personal' },

  // ── Health, Medicine & Wellness ───────────────────────────────────────────
  pharmeasy: { category: 'Health', tag: 'Personal' },
  netmeds: { category: 'Health', tag: 'Personal' },
  apollo: { category: 'Health', tag: 'Personal', defaultNote: 'Medicines' },
  'apollo pharmacy': { category: 'Health', tag: 'Personal' },
  medplus: { category: 'Health', tag: 'Personal' },
  '1mg': { category: 'Health', tag: 'Personal' },
  'tata 1mg': { category: 'Health', tag: 'Personal' },
  practo: { category: 'Health', tag: 'Personal', defaultNote: 'Doctor Consultation' },
  lybrate: { category: 'Health', tag: 'Personal' },
  'cult.fit': { category: 'Health', tag: 'Personal', defaultNote: 'Gym Membership' },
  cultfit: { category: 'Health', tag: 'Personal' },
  medicine: { category: 'Health', tag: 'Personal' },
  pharmacy: { category: 'Health', tag: 'Personal' },
  hospital: { category: 'Health', tag: 'Personal' },
  doctor: { category: 'Health', tag: 'Personal' },
  gym: { category: 'Health', tag: 'Personal' },
  clinic: { category: 'Health', tag: 'Personal' },
  dentist: { category: 'Health', tag: 'Personal' },
  lalpathlabs: { category: 'Health', tag: 'Personal', defaultNote: 'Lab Test' },

  // ── Education & Courses ───────────────────────────────────────────────────
  unacademy: { category: 'Education', tag: 'Personal' },
  byjus: { category: 'Education', tag: 'Personal' },
  "byju's": { category: 'Education', tag: 'Personal' },
  coursera: { category: 'Education', tag: 'Personal' },
  udemy: { category: 'Education', tag: 'Personal' },
  skillshare: { category: 'Education', tag: 'Personal' },
  'physics wallah': { category: 'Education', tag: 'Personal' },
  upgrad: { category: 'Education', tag: 'Personal' },
  school: { category: 'Education', tag: 'Personal', defaultNote: 'School Fee' },
  tuition: { category: 'Education', tag: 'Personal' },
  coaching: { category: 'Education', tag: 'Personal' },
  books: { category: 'Education', tag: 'Personal' },
  stationery: { category: 'Education', tag: 'Personal' },

  // ── Investment & Trading ──────────────────────────────────────────────────
  mutual: { category: 'Investment', tag: 'Personal' },
  zerodha: { category: 'Investment', tag: 'Personal', defaultNote: 'Stocks/Mutual Funds' },
  groww: { category: 'Investment', tag: 'Personal', defaultNote: 'SIP/Investment' },
  upstox: { category: 'Investment', tag: 'Personal' },
  'angel one': { category: 'Investment', tag: 'Personal' },
  angelone: { category: 'Investment', tag: 'Personal' },
  kuvera: { category: 'Investment', tag: 'Personal' },
  indmoney: { category: 'Investment', tag: 'Personal' },
  smallcase: { category: 'Investment', tag: 'Personal' },
  sip: { category: 'Investment', tag: 'Personal', defaultNote: 'SIP' },
  stocks: { category: 'Investment', tag: 'Personal' },
  crypto: { category: 'Investment', tag: 'Personal' },
  coin: { category: 'Investment', tag: 'Personal' },

  // ── Loans & Financial Services ────────────────────────────────────────────
  loan: { category: 'Loan', tag: 'Personal', defaultNote: 'Loan Payment' },
  emi: { category: 'Loan', tag: 'Personal', defaultNote: 'EMI Payment' },
  cred: { category: 'Bills', tag: 'Personal', defaultNote: 'Credit Card Bill' },
  slice: { category: 'Bills', tag: 'Personal' },
  'bajaj finserv': { category: 'Loan', tag: 'Personal', defaultNote: 'EMI' },

  // ── Housing & Maintenance ─────────────────────────────────────────────────
  rent: { category: 'Housing', tag: 'Household', defaultNote: 'House Rent' },
  maintenance: { category: 'Housing', tag: 'Household', defaultNote: 'Society Maintenance' },
  'society maintenance': { category: 'Housing', tag: 'Household' },
  plumber: { category: 'Housing', tag: 'Household' },
  electrician: { category: 'Housing', tag: 'Household' },
  carpenter: { category: 'Housing', tag: 'Household' },
  maid: { category: 'Housing', tag: 'Household', defaultNote: 'Maid Salary' },
  'urban company': { category: 'Housing', tag: 'Household', defaultNote: 'Home Services' },
  uc: { category: 'Housing', tag: 'Household' },

  // ── Donations & Charity ───────────────────────────────────────────────────
  temple: { category: 'Donations', tag: 'Personal' },
  church: { category: 'Donations', tag: 'Personal' },
  mosque: { category: 'Donations', tag: 'Personal' },
  gurudwara: { category: 'Donations', tag: 'Personal' },
  charity: { category: 'Donations', tag: 'Personal' },
  donation: { category: 'Donations', tag: 'Personal' },
  ngo: { category: 'Donations', tag: 'Personal' },
};

// ─── 2. UPI Apps & Wallets ──────────────────────────────────────────────────
export const UPI_APPS: Record<string, string> = {
  gpay: 'GPay', 'google pay': 'GPay', googlepay: 'GPay', 'g pay': 'GPay',
  phonepe: 'PhonePe', 'phone pe': 'PhonePe',
  paytm: 'Paytm', bhim: 'BHIM', cred: 'CRED',
  slice: 'Slice', amazonpay: 'Amazon Pay', 'amazon pay': 'Amazon Pay',
  mobikwik: 'MobiKwik', whatsapp: 'WhatsApp Pay', 'whatsapp pay': 'WhatsApp Pay',
  jupiter: 'Jupiter', fi: 'Fi Money', freecharge: 'Freecharge',
  navi: 'Navi', 'samsung pay': 'Samsung Pay', imobile: 'iMobile Pay',
  payzapp: 'PayZapp', supermoney: 'SuperMoney', bajajpay: 'Bajaj Pay',
};

// ─── 3. Comprehensive Bank Nicknames Directory ─────────────────────────────
export const BANK_NICKNAMES: Record<string, string> = {
  sbi: 'state bank', pnb: 'punjab national', hdfc: 'hdfc',
  icici: 'icici', axis: 'axis', kotak: 'kotak',
  bob: 'bank of baroda', canara: 'canara', 'yes bank': 'yes bank',
  indusind: 'indusind', idfc: 'idfc', rbl: 'rbl',
  federal: 'federal', ubi: 'union bank', 'union bank': 'union bank',
  'indian bank': 'indian bank', iob: 'indian overseas',
  uco: 'uco bank', bandhan: 'bandhan', au: 'au small',
  'paytm bank': 'paytm payments', 'airtel bank': 'airtel payments',
  dbs: 'dbs', citi: 'citi', hsbc: 'hsbc',
  'standard chartered': 'standard chartered', sc: 'standard chartered',
  'post office': 'post office', fino: 'fino', equitas: 'equitas',
  ujjivan: 'ujjivan', jana: 'jana', suryoday: 'suryoday',
  'south indian bank': 'south indian', sib: 'south indian',
  kvb: 'karur vysya', 'karur vysya': 'karur vysya',
  'karnataka bank': 'karnataka bank', jkb: 'jammu',
};

// ─── 4. Master Transaction Phrase Directory (300+ phrases) ──────────────────
export const TRANSACTION_PHRASES: string[] = [
  // Expense / Outflow starters
  'paid to ', 'paid for ', 'paid at ', 'payment to ', 'payment for ',
  'spent on ', 'spent at ', 'bought from ', 'bought at ', 'purchased from ',
  'ordered from ', 'expense for ', 'bill paid to ', 'bill payment for ',
  'recharge for ', 'subscription for ', 'fee paid to ', 'fees for ',
  'charges for ', 'deducted for ', 'cash withdrawn from ', 'withdrew from ',
  
  // Income / Inflow starters
  'received from ', 'received salary from ', 'salary received from ', 'salary from ',
  'income from ', 'credited from ', 'credited by ', 'got from ', 'got paid from ',
  'payment received from ', 'refund from ', 'cashback from ', 'interest from ',
  'dividend from ', 'freelance income from ', 'bonus from ', 'incentive from ',
  'reimbursement from ', 'deposited to ', 'added to ',

  // Transfer starters
  'transferred to ', 'transfer to ', 'sent to ', 'sent money to ', 'moved to ',
  'moved from ', 'transferred from ', 'transfer from ',

  // Payment Method Suffixes
  'via gpay', 'via phonepe', 'via paytm', 'via upi', 'via cash', 'via credit card',
  'via debit card', 'via net banking', 'using gpay', 'using phonepe', 'using paytm',
  'using upi', 'using cash', 'using credit card', 'using debit card', 'by gpay',
  'by phonepe', 'by paytm', 'by upi', 'by cash', 'from hdfc', 'from icici', 'from sbi',

  // Date Suffixes
  'today', 'yesterday', 'last monday', 'last tuesday', 'last wednesday',
  'last thursday', 'last friday', 'last saturday', 'last sunday', 'last week',
  'last month', '2 days ago', '3 days ago', '1 week ago', 'this week', 'this month',

  // Hinglish / Regional starters & phrases
  'diya ', 'mila ', 'aaya ', 'bheja ', 'kharcha ', 'nikala ', 'de diya ',
  'le liya ', 'pay kiya ', 'transfer kiya ', 'bhej diya ', 'mil gaya ',
];
